defaults:
  - stac: gcp
  - tiler: utm
  - scheduler: utm
  - deployer: gcp
  - builder: gcp
  - cloud: gcp
  - preparer: gcp
  - plugins: gcp
  - _self_
tasks:
  - build
  #- stac
  #- tile
  #- schedule
  #- prepare
  #- deploy
  #- plugins
overwrite: false
dataset_name: alumbrera
output: ./outputs/
hydra:
  run:
    dir: .
log_path: ${output}/main.log
credentials: ./oxeo-main-s1.json
gpd_input: ${output}/${dataset_name}.geojson
item_collection: ${output}/item_collection.geojson
tiles: ${output}/${dataset_name}_tiles.pkl
extraction_tasks: ${output}/extraction_tasks.pkl
start_date: 2017-01-01
end_date: 2021-01-01
constellations:
  - sentinel-2
  - landsat-8

